### ISSUE TITLE
Escape ampersand in attribute values like URLs

### ISSUE THREAD

**Issue by nicolashohm** [storyblok/storyblok-php-richtext-renderer#23]
We're users of storyblok and use this library in our PHP application. We parse and process the generated HTML with PHP's built-in DOM classes. 

Unfortunately, the HTML produced by the `Resolver` can't be parsed by `DOMDocument::loadHTML` because the ampersand is not escaped. In XML, ampersand needs to be escaped as `&amp;`, in HTML it's not necessary but recommended, to prevent [ambiguous ampersand.](https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-value) 

I took a brief look into this library, and it looks fairly easy to fix that. So before we implement some logic on our side to make the HTML working with the DOM classes, would you be interested in changing that in this lib? If yes, I'll provide a PR with fix and tests.

---

## Expected Behavior

Ampersands in attribute values are properly escaped like this:
```html
<a href="https://www.storyblok.com/?foo=bar&amp;bar=foo">
```

## Current Behavior

Ampersands in attribute values are not escaped, which leads to parsing errors if it's been parsed with PHP's DOM classes:
```html
<a href="https://www.storyblok.com/?foo=bar&bar=foo">
```

## Steps to Reproduce

```php
$data = [
    'type' => 'doc',
    'content' => [
        [
            'type' => 'paragraph',
            'content' => [
                [
                    'text' => 'test',
                    'type' => 'text',
                    'marks' => [
                        [
                            'type' => "link",
                            'attrs' => [
                                'href' => "https://www.storyblok.com/?foo=bar&bar=foo",
                                'uuid' => null,
                                'anchor' => null,
                                'target' => "_self",
                                'linktype' => "url",
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
$html = (new Resolver)->render($data);
// Prints: <p><a href="https://www.storyblok.com/?foo=bar&bar=foo" target="_self">test</a></p>
$document = new \DOMDocument();
$document->loadHTML($html);
// loadHTML fails with: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1
```

**Comment by ademarCardoso** [comment]
Feature added in the version [2.2.1](https://github.com/storyblok/storyblok-php-richtext-renderer/releases/tag/2.2.1).

Thanks to reporting 😄
