### ISSUE TITLE
Styled type (span) doesn't have anchor attribute

### ISSUE THREAD

**Issue by pknijff** [storyblok/storyblok-php-richtext-renderer#3]
We have encountered the following issue, when we add a CSS class in the rich text editor in Storyblok, we receive an error with the following message: `An exception has been thrown during the rendering of a template ("Notice: Undefined index: anchor").`.

_See the following piece of code:_
https://github.com/storyblok/storyblok-php-richtext-renderer/blob/a54d66074b9feaea2aa707fda248c266b1cd1cb3/src/Schema.php#L19

Here you'll see that even when it's a styled type, it calls the `get_link_styled()` function. But it is a span which doesn't have an anchor attribute. And so it fails.

A fix could be to introduce a separate function to style the span or reusing the `get_link_styled()` function and checking if the anchor key exists. My personal preference would be the first option.

**Comment by ademarCardoso** [comment]
Hi my friend @pknijff , thank you to submit this issue, i'm will investigate this problem now, i'm going to analize your sugestions, thanks!

**Comment by pknijff** [comment]
Hi @ademarCardoso, thanks for your effort, much appreciated!

**Comment by ademarCardoso** [comment]
Hi @pknijff , I created this [brach](https://github.com/storyblok/storyblok-php-richtext-renderer/tree/hotfix/styled-function) with the possible correction, if you want to test it and give me your feedback I appreciate it.

**Comment by pknijff** [comment]
Hi @ademarCardoso, I tested it and can confirm it works.

**Comment by pknijff** [comment]
Hi @ademarCardoso, any updates on this fix?

**Comment by pknijff** [comment]
I was checking your PR, and might I suggest to have an extra look at this part: https://github.com/storyblok/storyblok-php-richtext-renderer/pull/4/files#diff-8db9667fb5a2702c4e96d6ba0adf79bdR46.

The `if` check just before that line checks if an anchor is 0 or null, if that's the case the anchor is getting unset. The code will brak because of the `$node['attrs']['anchor']` check in the `if` statement just after it is being unset.

This is what the $node is containing after the unset:
`/application/symfony/vendor/storyblok/richtext-resolver/src/Schema.php:46:
array (size=2)
  'type' => string 'link' (length=4)
  'attrs' => 
    array (size=4)
      'href' => string 'https://www....' (length=42)
      'uuid' => null
      'target' => null
      'linktype' => null
`
Maybe it is a good idea to explicitly check if anchor exists?
`if (array_key_exists('anchor', $node['attrs']) && $node['attrs']['anchor']) {
      $attrs = $node['attrs'];
      $attrs['href'] = $attrs['href'] . "#" . $attrs['anchor'];
      unset($attrs['anchor']);
      $node['attrs'] = $attrs;
}`

**Comment by ademarCardoso** [comment]
Hi @pknijff, I'sorry for delay.

The if you are exemplifying, is to make the code semantics better ? I liked :)
Because if it is to remove the above `if`, this one, only this condition that you showed will not work, because the render will end up adding `anchor = "" ` in the tag structure `<a>`

**Comment by ademarCardoso** [comment]
Hi friend @pknijff, i'm merge the PR to solve the problem mentioneted in this issues, now i'm close this issue, if you have another problem, talk with me and open a new issue, thanks :)

**Comment by WesleySmits** [comment]
Hi @ademarCardoso,

My coworker @pknijff pointed out that the line `if (array_key_exists('anchor', $node['attrs']) && $node['attrs']['anchor']) {` throws an error because the anchor is unset a few lines above it. That's why the `array_key_exists()` was suggested to be added. 

We still have an issue on line 42 of the schema.php because 'anchor' is not a key in the array.

**Comment by ademarCardoso** [comment]
Hi @WesleySmits , thanks for the answer :) ; Now i understand the problem that your friend had mentioned, i will review the code of this lib to make sure it doesn't happen again, did you see any more problems?

**Comment by ademarCardoso** [comment]
Hi friend, the problems you mentioned in this issue were solved in the last [PR](https://github.com/storyblok/storyblok-php-richtext-renderer/pull/8)
