### ISSUE TITLE
Undefined index: anchor 

### ISSUE THREAD

**Issue by RicLeP** [storyblok/storyblok-php-richtext-renderer#6]
The last few commits have been throwing this error:
ErrorException
Undefined index: anchor 
vendor/storyblok/richtext-resolver/src/Schema.php:46

The last working commit for me is this: https://github.com/storyblok/storyblok-php-richtext-renderer/commit/3f096cc26a0bb86f8614933c4ddc233dcbdd254d

I still have this problem even after the anchor hot-fix commit here: https://github.com/storyblok/storyblok-php-richtext-renderer/commit/a54d66074b9feaea2aa707fda248c266b1cd1cb3

It seems to work if I check for the existence of the anchor in the node’s attributes. I don’t know enough about the package to know if this would have any other effects though.

This seems to fix it, but is anything needed on line 42 as well?

```php
// richtext-resolver/src/Schema.php, line 46

if (array_key_exists('anchor', $node['attrs']) && $node['attrs']['anchor'])
````

I made a pull request here: https://github.com/storyblok/storyblok-php-richtext-renderer/pull/7

---- UPDATED

Sorry, this other pull request looks better than mine, should have checked it first. https://github.com/storyblok/storyblok-php-richtext-renderer/pull/5/files

**Comment by ademarCardoso** [comment]
Hello my friend, thank you very much for opening the issue and sending the PR, I'm sorry for the problem caused in the last commits. I noticed that your PR and the eu is already open solve the same problem, I will review both and merge only 1.
Now, a small question, in the `tests` that are implemented, this error does not appear, would you have a use case for me to be able to set up a test for this? Again, thanks for reporting the problem. :)

**Comment by ademarCardoso** [comment]
Hi friend, the problems you mentioned in this issue were solved in the last [PR](https://github.com/storyblok/storyblok-php-richtext-renderer/pull/8)
