### ISSUE TITLE
Please tag a semver release

### ISSUE THREAD

**Issue by pscheit** [storyblok/storyblok-php-richtext-renderer#9]
so that we don't have to install from dev-master :)

Thank you!

**Comment by ademarCardoso** [comment]
Hi @pscheit, thanks to submit this idea, we will study and if possible add the **semver**, again, thanks for the tip :)

**Comment by pscheit** [comment]
it's easy: just create a tag 1.0.0 and let packagist crawl it. 
done

**Comment by ademarCardoso** [comment]
Thanks for the tip my friend @pscheit , it has always been implemented, anything just let us know.
